
services:
  - type: web
    name: stream-server
    env: ubuntu
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg nginx curl bash
      chmod +x render-start.sh
      chmod +x perfect_stream.sh
    startCommand: "./render-start.sh"
    plan: free
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
